### ISSUE TITLE
Language errors

### ISSUE THREAD

**Issue by ABarrosoG** [openhab/openhab-mycroft#70] opened 2019-08-05 21:06 UTC
Mycroft mounted:
`Raspberry pi 3 B+`
Distributor ID: Raspbian Description: Raspbian GNU/Linux 9.8 (stretch) Release: 9.8 Codename: 
`
stretch
Version Mycroft core:
mycroft-core 19.2.14
`
Error:
Language spanish work "Refresh Tagged Items"
Language spanish work  "List Items"
Language spanish what status not work
Language spanish on off command not work
dimmer and set temp I don't have items of that type or possibility to check it
(In English language everything works correctly)
Thanks!

**Comment by adocampo** [comment] 2019-08-06 07:57
First of all, are we speaking about Castillian or Latam? Is quite similar, but verbs precisely are pronounced different, as in Castillian speak mainly informal ("de tú") while in Latam predominantly speak formally ("de usted").
 
I cannot use openhab as the docker container doesn't seem to recognize my Zwave USB, so I'm using Home-Assistant. Anyway, as I've translated most of this skill, I've just checked out "what status" and "on|off" on https://translate.mycroft.ai 
__what status__
Try to say:
`"el elemento <Item> (a qué|cuál) (estado|temperatura|humedad|ajustes) (está|se encuentra)?"`
So you _must_ start with "el elemento", mention the item, and then one of the options between parenthesis. For example:
_el elemento bombilla a qué estado está?_ 

[I know that sounds _very_ awkward](https://github.com/openhab/openhab-mycroft/issues/57), but I couldn't order the sentence to make it sound natural because a limitation|bug on the translation tool, but @mortommy said it ordered manually on the code. So it should be working, anyway, try as I said and report back, please.

PS: Just modified this sentence to make it a bit more natural:
`el elemento (?P<Item>.*) (en qué|a qué|qué) (?P<RequestType>estado|temperatura|humedad|ajustes) (está|se encuentra|tiene)?`
On the next push of translations, it will be updated, or perhaps as @mortommy modified it manually, we should do a PR instead.

__on|off__
Looking at the translation site, it seems that the skill uses "turn" as verb and "on|off" as command which doesn't make any sense in Spanish, besides, the translator translated "turn" as "[giro](https://translate.mycroft.ai/es/mycroft-skills/translate/openhab-mycroft-es.po#filter=all&unit=85702&offset=0)", a word with a complete different meaning and absolutely nothing to do in home automation.
![image](https://user-images.githubusercontent.com/2266612/62520881-c1be6e80-b82e-11e9-9738-0c3bc117d253.png)
Looking further I see more problems, as 
![image](https://user-images.githubusercontent.com/2266612/62520965-efa3b300-b82e-11e9-8600-65febabb49ad.png)

Skill developer should use "turn on" and "turn off" separately and not rely in the model `verb + command` which only makes sense in english. I'm afraid this problem is reproducible in all romance languages and perhaps even in germanic ones.

**Comment by mortommy** [comment] 2019-08-08 06:35
Hi,
honestly I have no idea, I don't speak Spanish and I just accepted a PR. I think your PR was already merged.

**Comment by adocampo** [comment] 2019-08-08 08:47
What I say is that in english make sense to put the verb (put|switch|turn) separately, and the the action (on|off), so an english speaking person says for instance "turn on" when a spanish says "enciende", an english speaking just need to change the particle and say "turn off" when a spanish uses a complete different word "apaga". And that's untranslatable in any romance language while you put the verb "alone" and rely on the particle on|off to do the action, this particle is the `command` variable in the code.

[I can see is a requirement](https://github.com/openhab/openhab-mycroft/blob/master/__init__.py#L78) for the code to work properly. [And in this line](https://github.com/openhab/openhab-mycroft/blob/master/__init__.py#L188) I can see is not just mandatory to pass `on|off`, but also makes me thing this code would make impossible to work properly in any other language besides english. I've used a computer translator, but german and italian translations will fail just like spanish for the very same reason.

I know this isn't trivial, as most probably it will need a code rewrite, having in mind multi-language and specifying in `OnOffStatusKeyword.voc` for en-us:
```
turn on
turn off
switch on
switch off
put on
put off
```
So any language in the world can translate properly those particles, even if in that language there is a word for each and every combination.

**Comment by mortommy** [comment] 2019-08-12 11:24
@ABarrosoG could you give more information about the issues?
Thank you.

**Comment by ABarrosoG** [comment] 2019-08-12 11:52
I have stopped picroft. I used the raspberry to mount the octoprint system, I will have to wait to buy a new one.
Thank you.

**Comment by mortommy** [comment] 2019-08-12 15:58
ok. I'll close it, when you have the new one please open a new issue.
Thank you.

**Closed as completed by mortommy** 2019-08-12 15:58 UTC
